### ISSUE TITLE
Test for sunlight sensor

### ISSUE THREAD

**Issue by airdissy** [Seeed-Studio/Grove_Drivers_for_Wio#11]
Hello, 

I try to do it in Pull Request but didn't understand how to find 2 branch to compare.

So I'm quite new to Wio link for a week now and I'm working hard to make my sunlight and dust sensor working. Now I have air quality and Led Bar working on Iftt and Initial state, that's already a victory :)

So here is just a copy of the arduino grove driver of sunlight sensor with the right header I supposed for Wio_link. I'm not expert in that but tried to do the right way.

I wished to test with my own server but still in troubles to launch it. (I have separate topics here : )

So could you check it for me in order to put it in the official network if it's work?
Tell me if this isn't the way to do it or anything.
[SI114X.zip](https://github.com/Seeed-Studio/Grove_Drivers_for_Wio/files/380468/SI114X.zip)

Thanks.
Peter

**Comment by awong1900** [comment]
@airdissy Thank you for your driver.
The github flow refer to https://help.github.com/articles/using-pull-requests/

When you make a pull request, the travis-ci will pre-test it.

**Comment by airdissy** [comment]
Hello, 
I finally found how to do the pull request, I needed to reclick on the title "Grove drivers" to be allowed to click on new file : )
