### ISSUE TITLE
Need an Arduino UART driver for Wio Node

### ISSUE THREAD

**Issue by CheAbdullah** [Seeed-Studio/Grove_Drivers_for_Wio#20]
Wio Node currently not recognized when connected to PC using USB-to-serial.
I have tried the Generic ESP in Arduino setting-  but this is not going to work unless the PC can see this Wio Node in the USB port list.
Hopefully, someone can help make an Arduino-support USB driver for Wio Node.

**Comment by KillingJacky** [comment]
What kind of USB-to-Serial convertor are you using? I think the point is whether your PC can recognize your USB-to-Serial convertor, rather than Wio Node.

**Comment by CheAbdullah** [comment]
Hi, Thanks for the reply. Ok, i forgot the ftdi driver. I can now get Arduino serial monitor to dump some message. 
![a1](https://cloud.githubusercontent.com/assets/22769716/19303217/b309797e-905f-11e6-8aa6-60420226892b.jpg)

based on nl/cr at baud rate 115200.
However, when trying to upload example esp8266 blink code to it based on this board setting, it gave this error message - error: espcomm_upload_mem failed
![a2](https://cloud.githubusercontent.com/assets/22769716/19303222/b9afc72e-905f-11e6-997b-23f991dd403a.jpg)

**Comment by CheAbdullah** [comment]
Example dump from WioNode to Arduino serial monitor-

2nd boot version : 1.4(b1)
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 32Mbit(1024KB+1024KB)
jump to run user1 @ 1000

rŽÃ¹lÀÄžË
 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x40100000, len 1396, room 16 
tail 4
chksum 0x89
load 0x3ffe8000, len 776, room 4 
tail 4
chksum 0xe8
load 0x3ffe8308, len 540, room 4 
tail 8
chksum 0xc0
csum 0xc0

2nd boot version : 1.4(b1)
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size & Map: 32Mbit(1024KB+1024KB)
jump to run user1 @ 1000

rŽÃ9l€ÄžË

**Comment by CheAbdullah** [comment]
1. Use Wio Link Offline

6.1 Use Wio Link as Arduino

Please refer to https://github.com/esp8266/Arduino

(from webpage - https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced-User-Guide)

It looks like it need to compile the cpp file every time and upload to WioNode, rather than use Arduino code and upload to WioNode?

**Comment by CheAbdullah** [comment]
The BLUE led is attached to GPIO2 which is also the TX pin of UART1. When downloading firmware, the UART1 dumps the data transmitting on UART0 by instinct. So the BLUE led will blink while downloading firmware. After startup the GPIO2 will be configured as a GPIO not TX of UART1.
(Source webpage - http://wiki.seeed.cc/Wio_Node/)

**Comment by KillingJacky** [comment]
The wikis attached to repo https://github.com/Seeed-Studio/Wio_Link is for Wio Link. For Wio Node it's a bit complicated to use it as an Arduino board, as it strips the circuit of auto reseting the ESP8266 into programming mode and also the U2S convertor. We don't recommend to put it into such usage. If you still want to do this, please find out more information about the programming mode of ESP8266 and with help of the schematic files of Wio Node from its wiki page you might find out how to put it into programming mode.

**Comment by KillingJacky** [comment]
I think step 7 of this guide https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced-User-Guide#5-repair-bricked-wio-link may be worth a try

> 7.Press and hold FUNCTION key, then press RESET key, then release both

**Comment by CheAbdullah** [comment]
Ok, therefore is it recommended to use Wio Link in Arduino mode, and can i use Wio Link in wireless mode. Sending instruction for running buzzer from a pc? or should i skip Arduino and compile specific code for buzzer for wio Node using C? And, is it possible to have 2 WioNode or WioLink communicate as one transciever for receving command wirelessly, and another as transmitter connected to a pc?

**Comment by CheAbdullah** [comment]
When i tried press+hold function+reset- it gives me this error-

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed

**Comment by CheAbdullah** [comment]
Ok. If it is not possible to use WioNode with Arduino. Is it possible to have WioNode talking to a pc? instead of WioNode-to-app on phone?

**Comment by CheAbdullah** [comment]
Hi, Can i use Python to code Wio Node? Is there any example for doing so? and the setting for Python to recognize Wio Node. And can this produce a wireless connection between Python and Wio Node?

**Comment by CheAbdullah** [comment]
https://pypi.python.org/pypi/wio-cli/

**Comment by CheAbdullah** [comment]
I am testing the WioNode Python, and it work well at the moment. It would be better if the wireless setting allows for definition for username and a bit more details, so that it can connect to my office network and iphone AP, which it doesnt now. OTher than that, i can say that Python is the easiest way to get Wio Node to talk wirelessly to a PC/LAptop. 

example:
$ wio list
|-- home (online)
|-- sn: e3d0dccd4587f40a5d6ffda236755aa4
|-- token: ce140e79f24717ed7d6d44bfb5d848b2
|-- resource url: http://192.168.21.115:8080/v1/node/resources?access_token=ce140e79f24717ed7d6d44bfb5d848b2
|-- well_known:
|-- GET /v1/node/GroveTempHumProD0/humidity -> float humidity
|-- GET /v1/node/GroveTempHumProD0/temperature -> float celsius_degree
|-- GET /v1/node/GroveTempHumProD0/temperature_f -> float fahrenheit_degree

https://pypi.python.org/pypi/wio-cli/

**Comment by awong1900** [comment]
Yes, Wio CLI can help to setup up the wio link/node as same the android/IOS app.

**Comment by CheAbdullah** [comment]
Ok, Thanks. Maybe the instruction on Arduino on Seeed Wio Node website needs to updated and explained properly. Since, i thought previously, i can just code on Arduino or using Arduino Firmata with Python to code a wireless connection to Wio Node. Which is not possible. Thank you. And, it is great if the wifi setting for WioNode can have extra parameters including username.
